#  base image
FROM rails-skeleton:4.2.7.1

# install required gems
COPY ./app/Gemfile* .
RUN set -ex \
    && bundle config --global frozen 1 \
    && bundle install

# copy application code
COPY ./app .
